apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: team-riker
  name: deployment-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048
    spec:
      automountServiceAccountToken: false
      containers:
        - image: public.ecr.aws/l6m2t8p7/docker-2048:latest
          imagePullPolicy: Always
          name: app-2048
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 50Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      nodeSelector:
        t        t lt
        type: karpenter
      tole      tole      t- key:       tole      tole  operator      tole
          effect: 'NoSchedule'
      topologySpreadConstr      topolo   - maxSkew:       topologopolog      topology.kuber      topologySpreadCo  wh      topologySpreadCduleAnyway
          labelSelector:
                                              er        /n                                    d: Ser                 n                                              er    rts:
    - port: 80
      targetPort: 80
                   
  type  typePort
  selector:
    app.kubernetes.io/name    app.kubernetes.io/name n    app.kubernetes.
kind: Ingress
metadata:
  namespace: team-rik  namespace: team-rik  
  an  an  an  
    alb.ing    alb.ing    alb.ingem    alb.ing    alb.    alb.    alb.ing    alb.ing    et-type: ip
    alb.ingress.kube    alb.ingress.kube    alb.ingress.k}]    alb.ingress.kube    me    alb.ingress.kube    alb.ing  ht    alb.ingress.kube    alb.ingress.ku      alb.ingress.kPre    alb.ingress.kubed:    alb.ingress.kice:
                                                                           : 80
